name: testzin
favicon: null
layout_spectrum: 0.3059467989951372
typography_spectrum: 0.6509883292019367
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5473216036334634
  lightness: 0.3142784300725907
  saturation: 0.8086733140517026
  rhythmicContrast: 0.9153309012763202
purpose: []
